### Numpy

- Create Arrays
- Work with Matrices made easy
- Collection of Mathematical Operations

### Install Numpy
pip install numpy

In [5]:
import numpy as np

# create array using numpy
# create 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 Row and 5 Columns

array([[1, 2, 3, 4, 5]])

In [17]:
# 2D Array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


2

In [19]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element Wise Addition
print("Addition :",arr1+arr2)
#Element Wise Subtraction
print("Subtraction :",arr1-arr2)
#Element Wise Multiplication
print("Multiplication :",arr1*arr2)
#Element Wise Divison
print("Divison :",arr1/arr2)

Addition : [11 22 33 44 55]
Subtraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Divison : [0.1 0.1 0.1 0.1 0.1]


In [29]:
# Universal Functions
arr=np.array([1,2,3,4])
#square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#Natural Log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


In [31]:
# Array Slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:,1:3])

1
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [36]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [42]:
# Modify Array Elements
arr[0][0]=100

In [43]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [45]:
arr[1:]=100

In [46]:
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [47]:
#Statistical Concepts - Normalization
##Change Data to have Mean of 0 and Standard Deviation of 1
data=np.array([1,2,3,4,5])

In [48]:
np.mean(data)

np.float64(3.0)

In [49]:
np.std(data)

np.float64(1.4142135623730951)

In [52]:
normalized_data=(data-np.mean(data))/np.std(data)
normalized_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [54]:
print("Median",np.median(data))
print("Variance",np.var(data))

Median 3.0
Variance 2.0


In [58]:
# Logical Operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
data[(data>5) & (data<8)]

array([6, 7])