### ***Numpy***
1) ***Python Extension, adding support for large multi-dimensional arrays and matrix's, along with large library of high-level mathematical functions to operate on these arrays.***
2) ***This contains:***
    - _N-dimensional array object_
    - _Array slicing methods_
    - _Array reshaping methods_

### ***Arithmetic Operation cannot be applied on the lists***

In [2]:
#List1
list1: list[int]=[1,2,3,4]
#List2
list2: list[int]=[5,6,7,8]
#Trying to add the list elements
listsum: list[int]=list1+list2
#Instead we get Union of two lists
print(listsum)

[1, 2, 3, 4, 5, 6, 7, 8]


### ***Numpy - ndarray***
***Numpy main object is ndarray (homogenous multidimensional array).***
- _Dimensions - usually called axes_
- _Rank - number of axes/dimensions_

_Example:_
- _[9,1,-1] -> An array of **Rank 1** (1 Row and 3 Columns)_
- _[[10,0.21,-30],[1.9,7.4,1.9]] -> An array of **Rank 2** (2 Rows and 3 Columns)_

***If the List[0] of 2nd example contained 1 more list then it would have been 3 dimensional***

### ***Numpy Array Creation***
_There are couple of ways for creating arrays in Numpy:_
- _A Python list or tuples_
- _Using Functions that are dedicated to generating numpy arrays, such as arange, ones, zeros, linespace, etc_
- _Reading data from files_

In [2]:
import numpy as np
prices: list[int]=[345,789,900,120,560,348,456]
a1: np.ndarray=np.array(prices)
a1

array([345, 789, 900, 120, 560, 348, 456])

In [3]:
a1+10

array([355, 799, 910, 130, 570, 358, 466])

In [4]:
a1/2

array([172.5, 394.5, 450. ,  60. , 280. , 174. , 228. ])

In [5]:
prices: list[float]=[345,789,900,120,560,348,456.89]
a1: np.ndarray=np.array(prices)
a1

array([345.  , 789.  , 900.  , 120.  , 560.  , 348.  , 456.89])

In [6]:
prices: list=[345,789,900,120,560,348,456.89,"abc"]
a1: np.ndarray=np.array(prices)
a1

array(['345', '789', '900', '120', '560', '348', '456.89', 'abc'],
      dtype='<U32')

In [7]:
t1: tuple=(11,12,13,14,15)
a2:np.ndarray=np.array(t1)
a2

array([11, 12, 13, 14, 15])

In [8]:
type(a2)

numpy.ndarray

In [9]:
l1: list=[[1,2,3],[4,5,6],[7,8,9]]
a3: np.ndarray=np.array(l1)
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
type(a3)

numpy.ndarray

In [11]:
a3%2==0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [12]:
a3/2==0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [13]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### ***Numpy - Creating Array using built-in function***
- zeros(shape) -- creates an array filled with 0 values with the specified shape. The default dtype is float64.
- ones(shape) -- creates an array filled with 1 values
- arange() -- creates arrays with regularly increasing values
- linespace() -- creates arrays with a specified number of elements, and spaced equally between the specified beginning and end values
- eye() -- returns 2D array with ones on the diagonal and zeroes everywhere

In [14]:
import numpy as np
arr1=np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arr1=np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
arr2=np.zeros((4,5),dtype=int)
arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
arr2=np.zeros((4,5))
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
arr2=np.ones((4,5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
arr1=np.ones(10,dtype=int)
arr1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
arr1=np.arange(1,100)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
arr1=np.arange(1,100,2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [22]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr1.size

10

In [24]:
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
arr1.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [106]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [27]:
np.eye(5,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr1[2]

np.int64(3)

In [30]:
arr1[2]=11
arr1

array([ 1,  2, 11,  4,  5,  6,  7,  8,  9, 10])

In [31]:
del arr1[2]

ValueError: cannot delete array elements

### ***Numpy - ndarray Attributes***
- ndarray.ndim - Represents the number of dimensions(axes) of the ndarray.
- ndarray.shape - For a matrix with n rows and m columns, shape will be tuple(n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim

In [32]:
import numpy as np
arr1: np.ndarray=np.array([11,22,33,44,55])
#print(type(arr1))
arr2: np.ndarray=np.array([[11,56,23,90],[55,21,67,87],[90,16,18,93]])
print(arr1)
print(arr2)

[11 22 33 44 55]
[[11 56 23 90]
 [55 21 67 87]
 [90 16 18 93]]


In [33]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [34]:
arr1.shape

(5,)

***In the above example we can see that if the array is 1 dimensional, the length of the array is the number of rows in the shape attribute***
\
_which means that the in 1D array the elements are stored row-wise_\
arr1=\
[1,\
2,\
3,\
4,\
5]

In [35]:
arr2.shape

(3, 4)

- ndarray.size - The total number of elements in the array. This is equal to product of elements of shape.
- ndarray.dtype - Object describing the type of elements in the array. One can create or specify dtype's using standard Python types. Additionally Numpy provides types of its own. numpy.int32, numpy.int16 and numpy.float64 are some examples

In [36]:
arr1

array([11, 22, 33, 44, 55])

In [37]:
arr1.dtype

dtype('int64')

In [38]:
arr3: np.ndarray=np.array([1,2,3,4,5],dtype=np.int8)

In [39]:
arr3.dtype

dtype('int8')

In [40]:
arr3: np.ndarray=np.array([1123123123123213123,2,3,4,5],dtype=np.int8)

OverflowError: Python int too large to convert to C long

***Since np.int8 can store only till 8 bits i.e singed 8 bit integer can store (_<sup>singedbit</sup>) _ _ _ _ _ _ _ from -2<sup>7</sup> till 2<sup>7</sup> -1 (i.e from -128 to 127)***

In [41]:
arr3: np.ndarray=np.array([127,2,3,4,5],dtype=np.int8)

In [42]:
arr3: np.ndarray=np.array([1123123123123213123,2,3,4,5,2,3,4,5],dtype=np.int64)
arr3.dtype

dtype('int64')

In [43]:
arr3

array([1123123123123213123,                   2,                   3,
                         4,                   5,                   2,
                         3,                   4,                   5])

In [44]:
arr3.shape

(9,)

In [45]:
arr3.size

9

In [46]:
arr2

array([[11, 56, 23, 90],
       [55, 21, 67, 87],
       [90, 16, 18, 93]])

In [47]:
arr2.shape

(3, 4)

In [48]:
arr2.size

12

In [49]:
arr2.itemsize

8

In [50]:
arr2.dtype

dtype('int64')

In [51]:
arr3.dtype

dtype('int64')

In [52]:
arr1.dtype

dtype('int64')

In [53]:
arr3: np.ndarray=np.array([127,2,3,4,5],dtype=np.int8)
arr3.dtype

dtype('int8')

In [54]:
arr3.itemsize

1

- ndarray.itemsize - Gives the item size in bytes. It is the dtype size(bits)/8 => to get the size in bytes
- ndarray.nbytes - It provides the total number of bytes occupied by array. (Product of Itemsize by size attribute)

In [55]:
arr3

array([127,   2,   3,   4,   5], dtype=int8)

In [56]:
arr3.itemsize*arr3.size

5

In [57]:
arr3.nbytes

5

In [58]:
arr3.itemsize

1

In [59]:
arr3.size

5

In [60]:
arr3.shape

(5,)

### Numpy Random

In [61]:
import numpy as np
arr1=np.random.randint(1,5,10)
arr1

array([1, 2, 4, 3, 1, 4, 1, 3, 4, 4], dtype=int32)

In [62]:
arr1=np.random.randint(1,50,16).reshape(4,4)
arr1

array([[43,  2, 20, 27],
       [ 9, 12, 11, 21],
       [31, 46,  3, 24],
       [17, 13, 18,  6]], dtype=int32)

In [63]:
arr1=np.random.rand(5,3)
arr1

array([[0.93427688, 0.79126882, 0.94741456],
       [0.1093116 , 0.02810857, 0.98316384],
       [0.74554514, 0.5604153 , 0.94413142],
       [0.44256382, 0.22092763, 0.72779221],
       [0.15883033, 0.29783689, 0.05907986]])

In [36]:
import numpy as np
arr1=np.random.randn(5,3)
arr1.var()

np.float64(0.7827216853309585)

In [8]:
import numpy as np
arr1=np.random.randint(30,100,6)
arr1

array([54, 65, 45, 68, 43, 48], dtype=int32)

In [3]:
arr1**2

array([5625, 7056, 5329, 9604, 2401, 6241], dtype=int32)

In [38]:
arr1=np.random.randint(1,9,16).reshape(4,4)
arr2=np.random.randint(1,9,16).reshape(4,4)
arr1

array([[5, 3, 5, 4],
       [1, 5, 3, 1],
       [8, 3, 2, 3],
       [3, 1, 1, 2]], dtype=int32)

In [39]:
arr2
np.linalg.inv(arr2)

array([[-1.60173160e-01,  1.81818182e-01, -4.28571429e-01,
         2.38095238e-01],
       [-9.52380952e-02, -1.47188659e-18,  2.85714286e-01,
        -4.76190476e-02],
       [ 2.38095238e-01, -1.17750927e-17,  2.85714286e-01,
        -3.80952381e-01],
       [-1.94805195e-02, -4.54545455e-02, -2.14285714e-01,
         2.85714286e-01]])

In [6]:
arr1+arr2

array([[12, 10, 10, 13],
       [14,  9, 10,  9],
       [11, 11,  8,  4],
       [ 9,  9, 12,  8]], dtype=int32)

In [7]:
arr1-arr2

array([[ 4, -6, -2, -3],
       [ 2,  7, -4, -5],
       [-1, -5,  4, -2],
       [-1, -7,  0, -2]], dtype=int32)

In [8]:
arr1*arr2

array([[32, 16, 24, 40],
       [48,  8, 21, 14],
       [30, 24, 12,  3],
       [20,  8, 36, 15]], dtype=int32)

In [9]:
arr1.dot(arr2)

array([[ 93, 138, 100, 115],
       [108, 112, 122, 139],
       [ 79,  99,  69,  84],
       [ 73, 105,  61,  72]], dtype=int32)

In [10]:
arr1.transpose()

array([[8, 8, 5, 4],
       [2, 8, 3, 1],
       [4, 3, 6, 6],
       [5, 2, 1, 3]], dtype=int32)

In [11]:
arr1

array([[8, 2, 4, 5],
       [8, 8, 3, 2],
       [5, 3, 6, 1],
       [4, 1, 6, 3]], dtype=int32)

In [12]:
arr1.std()

np.float64(2.310810193417019)

In [13]:
arr1.mean()

np.float64(4.3125)

In [14]:
arr1.var()

np.float64(5.33984375)

In [15]:
arr1.__invert__()

array([[-9, -3, -5, -6],
       [-9, -9, -4, -3],
       [-6, -4, -7, -2],
       [-5, -2, -7, -4]], dtype=int32)

In [16]:
arr1

array([[8, 2, 4, 5],
       [8, 8, 3, 2],
       [5, 3, 6, 1],
       [4, 1, 6, 3]], dtype=int32)

In [17]:
np.min(arr1)

np.int32(1)

In [18]:
np.max(arr1)

np.int32(8)

In [19]:
arr1

array([[8, 2, 4, 5],
       [8, 8, 3, 2],
       [5, 3, 6, 1],
       [4, 1, 6, 3]], dtype=int32)

In [20]:
a1=np.random.randint(1,20,10)

In [21]:
a1

array([ 2,  2, 16,  7, 10, 17, 11, 12, 15,  4], dtype=int32)

In [22]:
a1[2:6]

array([16,  7, 10, 17], dtype=int32)

In [23]:
a1[2:6:2]

array([16, 10], dtype=int32)

In [1]:
#axis=0 means sum of per column
#axis=1 means sum of per row